package com.example.g6information.entily;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.g6information.entily.Userentily;

import com.example.g6information.entily.UserentilyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userentilyDaoConfig;

    private final UserentilyDao userentilyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userentilyDaoConfig = daoConfigMap.get(UserentilyDao.class).clone();
        userentilyDaoConfig.initIdentityScope(type);

        userentilyDao = new UserentilyDao(userentilyDaoConfig, this);

        registerDao(Userentily.class, userentilyDao);
    }
    
    public void clear() {
        userentilyDaoConfig.clearIdentityScope();
    }

    public UserentilyDao getUserentilyDao() {
        return userentilyDao;
    }

}
